version: 2

jobs:
  build_and_test: 
    docker:
      - image: circleci/openjdk:8u171-jdk
    
    steps:
      - checkout
      - restore_cache:
          key: auto-deploy-test-{{ checksum ".circleci/config.yml" }}
      - run:
          command: mvn verify -DexcludeLiveServerTests=true -Dmaven.javadoc.skip=true
      - persist_to_workspace:
          root: .
          paths:
            - .
      - run:
          shell: /bin/bash -eo pipefail -O globstar
          command: |
            mkdir -p artifacts/junit
            cp **/target/*.jar artifacts/
            cp -a **/target/surefire-reports/. artifacts/junit
      - store_artifacts:
          path: artifacts
      - store_test_results:
          path: artifacts/junit

workflows:
  version: 2
  build-and-test:
    jobs:
      - build_and_test


